$ is now a method of utils
windycom/windy-plugins pull request #26
Opened 2021-09-16 07:01 UTC by rittels

2021-09-24 14:00 UTC, mdorda requested changes

2021-09-24 14:00 UTC, mdorda commented on examples/07-multiple-files-plugin/soundingGraph.mjs
> +const {$} = _;
Please, use prettier to keep formatting consistent. Also, imports first, declarations below.

2021-09-24 14:00 UTC, mdorda commented on examples/11-mobile-demo/plugin.html
> +        const {$} = _;
Please, use prettier to keep formatting consistent. Also, imports first, declarations below.

2021-09-24 14:00 UTC, mdorda commented on examples/11-mobile-demo/plugin.html
> +            .style.backgroundImage = `linear-gradient(rgba(${bgVals.slice(0, 3)},0), rgba(${bgVals}) 60%)`;
Is there any change?

2021-09-24 14:00 UTC, mdorda commented on dist/plugin.js
>      "url": "git+https://github.com/windycom/windy-plugins"
Why so many changes in this file? Is it on purpose?

2021-09-25 10:07 UTC, closed without merging

2021-09-25 10:07 UTC, rittels commented
new PR